From 61501d44a5eda79bff7ada93c0bfa710e95bdc5c Mon Sep 17 00:00:00 2001
From: Shilin Victor <chrono.monochrome@gmail.com>
Date: Mon, 20 Aug 2018 22:57:43 +0300
Subject: [PATCH 237/296] RuntimeException when reading a serializable object

when ResovlerActivity is started and the 3rd party app
put an extra with a bad serial object. It will throw a
RuntimeException. Actually we don't want this exception
thrown because of the app's bad extra data
---
 core/java/com/android/internal/app/ResolverActivity.java | 12 +++++++++++-
 1 file changed, 11 insertions(+), 1 deletion(-)

diff --git a/core/java/com/android/internal/app/ResolverActivity.java b/core/java/com/android/internal/app/ResolverActivity.java
index ceb06f51110..925708a9fa9 100644
--- a/core/java/com/android/internal/app/ResolverActivity.java
+++ b/core/java/com/android/internal/app/ResolverActivity.java
@@ -385,7 +385,17 @@ public class ResolverActivity extends Activity {
     }
 
     protected String getReferrerPackageName() {
-        final Uri referrer = getReferrer();
+        Uri referrer = null;
+        try {
+            referrer = getReferrer();
+        } catch(RuntimeException e) {
+            if (e.getCause() instanceof ClassNotFoundException) {
+                Log.d(TAG, "Error getReferrer\n" + e);
+                return null;
+            } else {
+                throw new RuntimeException(e);
+            }
+        }
         if (referrer != null && "android-app".equals(referrer.getScheme())) {
             return referrer.getHost();
         }
-- 
2.11.0

